### ISSUE TITLE
player.play!(track) never continues

### ISSUE THREAD

**Issue by jaime1988** [Burgestrand/Hallon#108]
Hi, 

When I execute that and the songs ends, nothing happens, the continuing code isn't executed.

**Comment by Burgestrand** [comment]
I’m sorry to say, this seems like an issue with libspotify. The callback for when a song has finished is _never_ invoked by libspotify, and to make matters worse libspotify keeps delivering audio (lots and _lots_ of empty audio), even though the song has nothing more to play.

Turns out the libspotify v11 release has been buggier than any other release I’ve encountered so far. I’m not sure if there’s anything Hallon can do to work around this. :(

**Comment by jaime1988** [comment]
This is a very big problem then :( does this happen with al v11 releases? would it be possible to use v10 release? I suppose I will have to use old hallon versions, don't I?
Thanks for all

**Comment by Burgestrand** [comment]
Yes, I believe the only way to properly work around this problem is to use libspotify v10.0.x (I believe it is v10.0.11 — [I found the Mac OS X build](https://developer.spotify.com/download/libspotify/libspotify-11.1.60-Darwin-universal.zip)) with [Hallon v0.14.0](https://rubygems.org/gems/hallon/versions/0.14.0). Given that this is an old version, [things in Hallon have changed since v0.14.0](https://github.com/Burgestrand/Hallon/compare/v0.14.0...HEAD), so make sure to read [the right documentation for v0.14.0](http://rdoc.info/github/Burgestrand/Hallon/v0.14.0/frames).

Luckily, Hallon v0.14.0 had support for audio.

I’ve talked to a friend however, and he reports getting the end_of_track callbacks, so I’m not sure where or why it is disappearing. In the meantime, though, I’d take my chances on the old version.

**Comment by jaime1988** [comment]
Ok, I will try with v0.14.0 then.

Thanks for all 
Congratulations for your awsome job!

**Comment by Burgestrand** [comment]
I’ve found that the callback is still invoked, but in another way than previously. I’m trying to implement it at the moment.

**Comment by jaime1988** [comment]
Oh!! very good news :) I will wait for that. I have had problems with the player.stop method too, I suppose it will have the same origin.

**Comment by Burgestrand** [comment]
I’ve updated Player#play! to work for now in the latest Hallon master. The current master (4f8431c475c4cd9aa080a9effa98821073b3e93e) is somewhat stable. It’s just missing the two new features from libspotify before I’m releasing v0.16.0 (which has taken longer than expected :O!), so it should be alright to use it for now.

I also fixed the playing_audio example. :)
