### ISSUE TITLE
Tracks added callback, adder unknown of track added

### ISSUE THREAD

**Issue by edwinvdgraaf** [Burgestrand/Hallon#127]
Hi

First of all nice work on this libary, works very well and nice. I just have one issue which kept me up for two evenings and don't have a solution or could come up why this would work as intended. The case is the following, based on the precondition that I have a callback once tracks are added to a certain playlist. https://gist.github.com/3086814
- User adds a track
- Systems calls callback
- Tracks in playlist.each do |track| track.adder => #pointer end
- _However; the track added by the user and triggering the callback; track.adder => nil

This happens only for the track that is added to the playlist, on the next callback it has a adder. Perhaps this problems comes due to a wrong use/understanding of the callback mechanism. However, I just can't find a solution. 

Please let me know if I can be of any help!

Thanks

**Comment by Burgestrand** [comment]
Hi!

This is a long answer. I’m not sure if it answers your question, but maybe it helps. I _can_ tell you that your issue is a result of how libspotify behaves with it’s callbacks.

The [official libspotify documentation](https://developer.spotify.com/technologies/libspotify/docs/12.1.45/structsp__playlist__callbacks.html#a16c3e5758f8f73f5900de4b88424f85e) on this callback is not particularly helpful, and tells us nothing of which expectations we can have on the tracks given to the callback. I’ve experimented a bit with them, however, and here’s my findings.

``` ruby
playlist = session.container.load.contents[0]

playlist.on(:tracks_added) do |tracks, position|
  # 1.
  new_tracks = playlist.tracks[position, tracks.size]
  new_tracks.each do |track|
    puts "#{track.adder} added #{track.name} at #{track.added_at}"
  end
end

# 2.
playlist.load

# 3.
track = Hallon::Track.new("spotify:track:1HRou9uDSpN33NfAphyy3D").load

# 4.
playlist.insert(track)
```

1) First off, loading objects inside the callback block can be strange at times. Since load will ask the session to process events, and processing events might fire a callback, you might trigger a callback when you are inside the callback. Essentially you might end up calling the callback for the last track added, from inside the first track. So, inside anywhere here at point 1, avoid calling `load` or `session.process_events` as it may cause strange things happening in strange order.

2) Now, at this point we have asked Hallon to call the block at 1 when a track is added to a playlist. If the playlist already has tracks in it since before, the tracks_added callback _will_ fire once for each track already in the playlist. I’ve found that with an empty cache (especially), the tracks in these callbacks will have no adder and no added_at. In fact, it might have no data about the track at all (i.e. track is not loaded)!

```
[10] pry(main)> playlist.load
added Mystery of Life at 1970-01-01 00:00:00 UTC
added  at 1970-01-01 00:00:00 UTC
added  at 1970-01-01 00:00:00 UTC
added  at 1970-01-01 00:00:00 UTC
added  at 1970-01-01 00:00:00 UTC
```

3) Even if we remove point 2, the same thing might happen as a result of loading the track in point 3. This is because of the way libspotify works. It will load _all_ objects, and sync _everything_ when you let the session process events.

4) All my trials that happen at this point have shown the correct output from the tracks_added callback, e.g. “&lt;Hallon::User address=0x7fb963b87580> added Mystery of Life at 2012-07-11 22:44:45 UTC”. I cannot guarantee it will always work this way: I simply don’t know, and the documentation for libspotify does not say.

Sorry I could not have a better answer for you at this time. :(

**Comment by Burgestrand** [comment]
Closing on lack of activity; I’ll have to assume the answer is sufficient, sorry if this is not the case!

**Comment by edwinvdgraaf** [comment]
Thank you very much for you response. Due holidays haven't been able to answer before, but basically got around it by looking it up in the playlist. It requires a loop over all items in it, so not really efficient but does the trick.
