### ISSUE TITLE
200 track limit on search results

### ISSUE THREAD

**Issue by ghost** [Burgestrand/Hallon#128]
I'm writing a program to search for and organize the entire spotify library (or at least a large portion of it) for visualization purposes, so I'm using libspotify via Hallon to search for various tracks. When using the Search object to return a list of tracks/artists/albums, the max the list contains is 200, even if the corresponding item in the options hash is set to something higher than 200 (if it's set to something lower, then the list contains that amount). For example, if I do something like 

options = {:artists => 240}
search = Hallon::Search.new("genre:soul", options).load
artists = search.artists

the artists array will only have 200 items in it. I know the search query actually returns more than 200 artists because artists.total will return a number larger than 200. Is 200 an intentional limit imposed on the size of the search result list? Is there any way to get around this?

**Comment by Burgestrand** [comment]
Oh, this is due to paging of libspotify itself. Any given search has a limit of how many items it will return for the results — it appears this limit is currently set at 200. There is no mention of this number anywhere in the official documentation, so I would not put too much trust on this magical number.

To retrieve _all_ results (say… artists 0…N), you’ll have to compare `search.artists.size` to `search.artists.total` — if the total is larger than the current size, there are additional artists to find by doing the same search again but with a higher `artists_offset` option.

So, say you want all artists for a given search, you’d do something similar to this:

``` ruby

all_artists = []
offset  = 0

loop do
  search  = Hallon::Search.new("genre:soul", artists: 1000, artists_offset: offset).load
  artists = search.artists
  puts "#{artists.size} for offset #{offset} of total #{artists.total}"
  all_artists.concat(artists.to_a)
  offset += artists.size
  break if offset >= artists.total
end

p all_artists
```

**Comment by ghost** [comment]
This works perfectly for what I need, thanks.

**Comment by Burgestrand** [comment]
@cameron-erdogan You’re welcome :)
