### ISSUE TITLE
Hallon segfaults on :create_session on Heroku

### ISSUE THREAD

**Issue by deiga** [Burgestrand/Hallon#129]
Hi,

I'm trying to deploy my software to Heroku and it segfaults everytime.

Here is my tracelog:
http://pastie.org/4411665

my app is https://github.com/deiga/Spotilist/tree/develop

Can you tell me if this is a problem with Hallon or something else entirely?

**Comment by Burgestrand** [comment]
Hi!

I’m on my way out, so I just stopped by to say I’ll have a look at this later this evening. Without looking at it too much I would guess that the libspotify version used is not v12.1.51, or that it’s for another architecture than Heroku (32bit vs 64bit).

I’ll be on this in ~6 hours or so. :)

**Comment by Burgestrand** [comment]
Hey again. I’m fairly certain this is because the application key sent to Hallon (and thus, libspotify) was actually the path to your application key. If you read the application key from the path pointed to by ENV['SPOTIFY_APPKEY'] it should work. I managed to reproduce the crash locally and after the change it no longer crashes.

I sent a pull request to you. Hope you don’t mind :)

**Comment by deiga** [comment]
Thid can't be it, as I actually put the binary string into the ENV variable and not the path to it...

**Comment by Burgestrand** [comment]
@deiga it’s entirely possible (close to extremely probable) that your application key contains null bytes (i.e. 0x00), and afaik you cannot put these bytes in environment variables, they’ll be ignored. In fact, if you try to set an environment variable in Ruby to a string containing a null byte an error is raised. Either way, because of this your application key is likely to be shorter than expected, and libspotify will crash.

You can test the thesis above by doing this:

```
ruby -e 'p ENV["SPOTIFY_APPKEY"] == IO.read("/path/to/spotify_appkey.key")'
```

It should output true.

But! You could probably pull this off if you Base64-encoded the application key beforehand, and Base64-decoded it in your application. That should allow you to put the application key in an environment variable.

**Comment by deiga** [comment]
Okay, your right. On all my machines the APPKEY works as an env variable, but not on heroku.
Need to get an idea how to get the appkey to heroku then...

**Comment by Burgestrand** [comment]
@deiga I updated [hallon-heroku](https://github.com/Burgestrand/hallon-heroku) ([commit 1bdf9fc33](https://github.com/Burgestrand/hallon-heroku/commit/1bdf9fc33eb7e9e009727d007082700b628c47a1)) just now to do this very thing. It encodes the application key in base64, and decodes it in base64 on the server. The updated README shows how to configure both Heroku and your local machine with this.

It also uses the latest master of Hallon, which no longer requires the spotify-heroku hack. libspotify is included as a gem, so it no longer requires manual installation!

Let me know if it works for you so I may close this issue. :)

**Comment by deiga** [comment]
This resolves the issue. Thank you! :)

**Comment by Burgestrand** [comment]
Sweet! Thanks for reporting in. :)
