### ISSUE TITLE
Add Wiki page for 'How to test an application that is using Hallon'

### ISSUE THREAD

**Issue by joshmcarthur** [Burgestrand/Hallon#132]
Hey @Burgestrand,

First of all, thanks for this gem. Starting off a project that I thought would be daunting and full of difficulty turned out to be a delight to code, due in no small part to Hallong. So thanks!

Last week, I wrote a quick Rails application called On the Spot (https://github.com/joshmcarthur/on-the-spot)  - it's used at my work, similar to Play - everyone can jump on, and add the tracks they want to listen to, see what's coming up, etc. It's working really well, and is already been adopted pretty widely.

I'm currently in the process of refactoring my code and retro-fitting specs, and I would be very interested in the process that I need to go through to 'stub' out Hallon the same sort of way as the library itself does when running it's own specs (which I've taken a look at). I can see that you're using `libmockspotify`, and I can see (roughly) how you are loading it and setting it up, but because the library is stubbing out itself, I can't quite make the leap to see how I might use `libmockspotify` from my specs to speed up how long they take to run, and remove the dependency for the app keys and login credentials to be around for them to run.

Whether this might just be a couple of pointers in this issue, or a full-blown Wiki page, I don't really mind - however, I can see that a bit more documentation around how to test an application that is using Hallon as a dependency might come in handy for other developers

**Comment by Burgestrand** [comment]
Considering how Hallon works right now: stub out Hallon. Hallon is an external service that you rely on, and you should assume Hallon will place the right calls with the right parameters to libspotify when invoked. You should assume Hallon works and has it’s own tests. You also need to be careful to not stub out calls that don’t exist (say, if they are removed in another release of Hallon and you upgrade), and also that you pass the right number of parameters.

Ideally you’d stub out the spotify gem, but that is trickier. It requires knowledge of which calls Hallon place on spotify for any given method call, and what return values are expected, and as such it requires knowledge of how the spotify library is expected to behave from Hallon’s point of view. Stubbing out the Spotify gem is something I would have done for Hallon if I did not write libmockspotify. I wrote libmockspotify to catch implementation errors in Hallon that could/would cause segfaults or memory corruption, and not _really_ for testing libspotify. When you use Hallon, causing the kind of errors that libmockspotify allows me to catch should not be possible.

Hallon might be able to supply some kind of testing-only thing in the future, but because of the way Hallon works at the moment I don’t think it’s possible until I’ve managed to do my great cleaning of Hallon. There’s simply too much complexity, too many branches to take in Hallon, for it to be feasible. You also have to take great care with these testing-only addition things to not stray off from the real implementation, as most of the time these testing-only things turn out to plain suck and not really work in the same way the library does, rendering your tests useless.

I added a tiny wiki page with more or less the same answer: https://github.com/Burgestrand/Hallon/wiki/How-to-test-an-application-that-is-using-Hallon
