### ISSUE TITLE
Lock in Hallon::Session.initialize

### ISSUE THREAD

**Issue by bitboxer** [Burgestrand/Hallon#137]
If I start a second server instance on the same machine and call Hallon::Session.initialize , the method will never return and freeze my app. 

I have read about the forking issue, but does that mean that a second, complete separate server instance, can't be started on the same machine?

**Comment by Burgestrand** [comment]
I would guess this is because you have not changed the cache directories used by libspotify. You cannot use the same cache directories for two processes running libspotify at the same time.

You can change the cache directories as an option given when initializing the session. Please see the API reference on how: http://rdoc.info/github/Burgestrand/Hallon/Hallon/Session#initialize-class_method

I'm writing this on a phone on the go, so please excuse my brevity.

**Comment by Burgestrand** [comment]
I'd assume it's mainly settings_location that needs to be changed.

**Comment by bitboxer** [comment]
Thanks for your fast response! 

After setting settings_location AND cache_location, it works. Maybe you could add that in the Readme for others.

**Comment by Burgestrand** [comment]
Appears what you have your settings_location configured to does not matter, as long as cache_location differs. Interestingly enough, cache_location can be set to an empty string to disable the cache altogether.
