### ISSUE TITLE
Getting the number of subscribers of a playlist doesn't seems to work

### ISSUE THREAD

**Issue by verlinden** [Burgestrand/Hallon#139]
Hi,

I've tried to get the total number of subscribers of several playlist without success :/

Here is an example with a popular playlist with 5K+ subscribers: (login code omitted) 

``` ruby
playlist = Hallon::Playlist.new("spotify:playlist:1IeVJa1NQcpJBtKhAwrUXx")
playlist.load
playlist.name
=> "Lady Gaga: The Complete Collection"
playlist.total_subscribers
=> 0
playlist.subscribers
=> []
```

Is it something I'm doing wrong here ?
Thanks

**Comment by Burgestrand** [comment]
On Tuesday, 15 January 2013 at 10:00, Steve Verlinden wrote:

> playlist = Hallon::Playlist.new("spotify:playlist:1IeVJa1NQcpJBtKhAwrUXx")
> playlist.load playlist.name => "Lady Gaga: The Complete Collection" playlist.total_subscribers => 0 playlist.subscribers => []

Hi! Sorry, I’m writing this mail in a hurry so I don’t have time to provide a working example.
Playlists come with no initial subscriber information; instead you have to ask libspotify to fetch
the subscriber information for you, and wait until that is available. There is no good way to poll
for it in libspotify (e.g. no subscribers_loaded), and instead it’s entirely focused on listening for
callbacks like the rest of libspotify.

So, the call you’re after is here:
https://developer.spotify.com/technologies/libspotify/docs/12.1.45/group__playlist.html#ga9ebbf147230b3ca98b68e556cf24e6bd

In Hallon it’s named just #update_subscribers on a Playlist:
http://rdoc.info/github/Burgestrand/Hallon/Hallon/Playlist#update_subscribers-instance_method

— Kim

**Comment by verlinden** [comment]
Hi,

Hmmm thanks, but I don't figure how to do it.
When I look into the libspotify doc they say that when you call sp_playlist_update_subscribers it will invoke the "subscribers_changed" callback.

Here is my code :

``` ruby
playlist = Hallon::Playlist.new("spotify:user:thecompletecollection:playlist:1IeVJa1NQcpJBtKhAwrUXx")
playlist.load
playlist.name
=> "Lady Gaga: The Complete Collection"

playlist.on(:subscribers_changed) do
  puts "this never prints"
end

playlist.update_subscribers
playlist.total_subscribers
#=> 0
```

Also when I look the playlist on your heroku app : http://hallon.herokuapp.com/spotify:user:thecompletecollection:playlist:1IeVJa1NQcpJBtKhAwrUXx
It shows 0 subscribers, so I'm wondering if you already have succeeded fetching the correct subscribers count ?

I think I need your help on this, could you provide one code sample when you'll have little time ?
Regards,
Steve

**Comment by Burgestrand** [comment]
libspotify has two kinds of callbacks: those that are always fired from a different thread, at pretty much any time (I believe only the music-playing related callbacks), and callbacks that are fired as a result of calling [process_events](https://developer.spotify.com/technologies/libspotify/docs/12.1.45/group__session.html#gaff27cb730db6debf55e750e39e7fadd7). For libspotify to be able to do any work (even just downloading track or playlist information), Session#process_events needs to be called. This is what [#load](http://rdoc.info/github/Burgestrand/Hallon/Hallon/Loadable#load-instance_method) does on all loadable objects. The reason it is like this is because libspotify was written with an event loop in mind, where you can just pop in a call to process_events from time to time, but it doesn’t fit quite well with a synchronous-like library like Hallon (you’d want a proper event-thingy-like framework, really).

Anyhow; after the call to #update_subscribers, you need to call Session#process_events (one or many times, it’s impossible to tell how much), and your update_subscribers callback will eventually fire. Once it has fired, you should have your first set of subscriber information. It is entirely possible that your update_subscribers callback will fire multiple times in the future as subscriber information is changed.

As for code, something like this might work (I’m not entirely sure, libspotify’s guarantees are not well-defined):

``` ruby
pl = Hallon::Playlist.new("spotify:user:thecompletecollection:playlist:1IeVJa1NQcpJBtKhAwrUXx")
pl.update_subscribers
pl.wait_for(:subscribers_changed) { |event| event == :subscribers_changed }
p pl.total_subscribers
```

**Comment by verlinden** [comment]
Hi,

Thank you, your code sample works :-) :+1:

**Comment by Burgestrand** [comment]
Great. :)
