### ISSUE TITLE
Playlist removal

### ISSUE THREAD

**Issue by rilla** [Burgestrand/Hallon#150]
How do you delete a playlist? If it's not supported yet, I might need to implement it myself. Any tips would be greatly appreciated.

**Comment by Burgestrand** [comment]
You can't delete playlists in Spotify. You can only remove them from your list of playlists (that is what the client does when you click delete).

**Comment by rilla** [comment]
Oh, but... does that apply to lists created by myself too?

Also: what is the recommended way to remove a playlist from a container? PlaylistContainer#remove asks for an index, and I don't have one when initializing a Playlist by uri.

Thanks, and by the way - thanks for this awesome gem.

**Comment by Burgestrand** [comment]
Yes, playlists in spotify cannot be deleted, no matter who created them. Even playlists you created years ago and then deleted in the desktop client is still floating around in cyberspace, waiting for somebody to listen… :)

As far as removing a playlist from a container you’d probably have to iterate through the contents of that container to find the index of the playlist you wish to remove, and then call remove on that index. It’s been a while since I was in the Hallon code, but I believe that’s how it would be done at the moment.
