### ISSUE TITLE
throwing exception is not a valid spotify link URI or pointer

### ISSUE THREAD

**Issue by ppcano** [Burgestrand/Hallon#53]
Getting image URI throws an exception in some edge cases ( ex: spotify:album:3JFryzZ2dByJ7Z2Ik2fVua)

**album.cover(false).to_str**
# <Spotify::Pointer address=0x00000000000000> is not a valid spotify link URI or pointer

~/.rvm/gems/ruby-1.9.2-p180/gems/hallon-0.9.0/lib/hallon/base.rb:77:in `to_pointer'
~/.rvm/gems/ruby-1.9.2-p180/gems/hallon-0.9.0/lib/hallon/link.rb:31:in`initialize'
~/.rvm/gems/ruby-1.9.2-p180/gems/hallon-0.9.0/lib/hallon/album.rb:90:in `new'
~/.rvm/gems/ruby-1.9.2-p180/gems/hallon-0.9.0/lib/hallon/album.rb:90:in`cover'

**Comment by Burgestrand** [comment]
Thanks for the report; I’ll look at it once I get home in ~2 hours!

**Comment by Burgestrand** [comment]
Actually. I know what’s causing this. The fix is easy, but I believe there might be more places where this error might appear in. I’ll see if I can release a minor version of Hallon to fix this issue tonight.

Essentially, this line needs to be changed: https://github.com/Burgestrand/Hallon/blob/443c854fe48e3a4dc180126d1e0cdf33b3656d1c/lib/hallon/album.rb#L90

I’d like to add a test for it as well however, so it’ll have to wait until I get home.

**Comment by Burgestrand** [comment]
Released v0.9.1 for Hallon with this fix (amongst other things): https://rubygems.org/gems/hallon/versions/0.9.1
